; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_Hometown
	dba Music_Pokedex
	dba Music_Club3
	dba Music_SeelStage
	dba Music_Club2
	dba Music_BlueField
	dba Music_Cinnabar
	dba Music_RedField
	dba Music_Lavender
	dba Music_Obla
	dba Music_MuseumGuy
	dba Music_MeetRival
	dba Music_SurfingPikachu
	dba Music_CardPop
	dba Music_PkmnHealed
	dba Music_Blue
	dba Music_Ishihara
	dba Music_GRBlimp
	dba Music_GROverworld
	dba Music_Fort2
	dba Music_DuelTheme2
	dba Music_WildBeast
	dba Music_CatchEmBlue
	dba Music_Nuzzles
	dba Music_MatchVictory
	dba Music_BoosterPack
	dba Music_EndCredits
	dba Music_SlowMoon
	dba Music_RBYCredits
	dba Music_NameEntry
	dba Music_Cherry
	dba Music_Rocken
	dba Music_TCG2GameCorner
	dba Music_Surf
	dba Music_Club1
	dba Music_Wacky
	dba Music_GRCastle
	dba Music_PissyPamper
	dba Music_OceanWinter
	dba Music_SonicBoom
	dba Music_GastlyInTheGraveyard
	dba Music_HereComesGR
	dba Music_MeetEvilTrainer
	dba Music_MeetFemaleTrainer
	dba Music_MeetMaleTrainer
	dba Music_Blue
	dba Music_Ronald
	dba Music_RocketBattle
	dba Music_MeowthStage
	dba Music_Imakuni2
	dba Music_DuelTheme1
	dba Music_DuelTheme3
	dba Music_Hero
	dba Music_Academy
	dba Music_Unatco
	dba Music_SadAlex
	dba Music_PinkFlash
	dba Music_SlowMoon

